### PR TITLE
Resolves #7 Dockerization

### LINKED ISSUE #7: Create CYB docker image

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I'm reviewing this on https://gitpod.io/#https://github.com/pondersource/CYB/pull/8

**Comment by MahdiBaghbani** [comment]
@michielbdejong yes https seems to be problematic for horizon dashboard.

I try to solve it now.

Screenshot from 2022-11-10 22-49-41

**Comment by michielbdejong** [comment]
Ah, horizon "thinks" it's running on http. See https://github.com/laravel/horizon/issues/631

**Comment by michielbdejong** [comment]
Horizon assets fixed now :)
It will now probably break if you try to run it outside gitpod but then you will just see broken icons which will be less annoying than huge icons :)

**Comment by MahdiBaghbani** [comment]
@michielbdejong Nice! so there is the problem!
maybe we can fix it by providing an ENV variable inside PHP to instruct it which scheme to use, then we can tell our container if its on localhost or on gitpod by an ENV variable like:
```bash
-e HTTPS=ON
```

**Comment by michielbdejong** [comment]
@yasharpm Can we merge this into main now?
Note that #10 was built on top of this, so the whole Dockerisation work was merged into the queue branch, but this is still not merged into main.

**Pull request merged**
